# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
target 'aletter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aletter
pod 'SDWebImage'
pod 'LKDBHelper'
pod 'AFNetworking'
pod 'YTKNetwork'
pod 'Reachability'
pod 'Masonry'
pod 'MJRefresh'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'CRToast'
pod 'ReactiveViewModel'
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
pod 'YYText'
pod 'YYImage'
pod 'UMCAnalytics', '~> 5.5.0'
pod 'UMCShare/Social/ReducedWeChat', '= 6.9.3'
pod 'UMCShare/Social/ReducedQQ', '= 6.9.3'
pod 'UMCShare/Social/ReducedSina', '= 6.9.3'
pod 'Bugly', '~> 2.5.0'
pod 'JPush', '~> 3.0.9'
pod 'AliyunOSSiOS', '~> 2.10.4'

pod 'FLAnimatedImage'
pod 'SDWebImage/GIF'
#pod 'SDWebImage/WebP'

  target 'aletterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aletterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
